language: ruby
cache: bundler
sudo: true
gemfile:
  - test/support/Gemfile
rvm:
  - 2.0
  - 2.1
  - 2.2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3ba4761e5efe291965bf
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
script: bundle exec rake foodcritic